### ISSUE TITLE
Weekly meeting time change

### ISSUE THREAD

**Issue by vincenzocoia** [UBC-STAT/stat545.stat.ubc.ca#48]
Hi @UBC-STAT/stat545 team, I won't be able to make Mondays at 11am work anymore for our weekly meetings. Can we meet at 10am instead?

**Comment by dy-lin** [comment]
Are they going to be 10-11? 30 minutes seemed a bit tight last week, but maybe it's because it's the beginning of the semester

**Comment by wvictor14** [comment]
10 is fine for me

**Comment by vincenzocoia** [comment]
> Are they going to be 10-11?

I think they should be, judging by last week's meeting.

> but maybe it's because it's the beginning of the semester

Probably right. I don't think we'll need so long in a few weeks from now.
