### ISSUE TITLE
Lectures

### ISSUE THREAD

**Issue by vincenzocoia** [UBC-STAT/stat545.stat.ubc.ca#49]
Hi @UBC-STAT/stat545 team -- two questions and some good news here.

1. Can someone deliver the lecture on Thursday, October 8? I won't have wifi that day.
    - Topic: fitting models in R. This does not go into statistical details -- the heart of it is (1) model-fitting functions typically taking the form of `function(y ~ x1 + ... + xp, data, settings)`, (2) the `predict()` generic, and (3) the `broom` package.
2. Are any of you interested in delivering any other lectures? I like to give my TA's the opportunity to lead lectures.
   - I can participate as either a moderator or as a co-instructor, whatever you choose.

PS: We'll be getting additional help with writing the worksheets! I'm still waiting to hear about the start date and who the new team members are, but I have some ideas as to how they would integrate into our workflow.

**Comment by wvictor14** [comment]
If there is no one else interested I'd be happy to fill in for October 8th! Let me know if you have content already prepared / want help with developing that.
