### ISSUE TITLE
Week 3 guidance

### ISSUE THREAD

**Issue by vincenzocoia** [UBC-STAT/stat545.stat.ubc.ca#52]
@sciclic For Week 3, I think they should read https://stat545.com/dplyr-intro.html for the dplyr lecture -- it closely matches what we'll be doing -- except I'm not sure whether it has tidyselect functions.

**Comment by vincenzocoia** [comment]
(Oops -- I copied the wrong link previously -- fixed now)

**Comment by sciclic** [comment]
Oops, I didn't see this but I think I added that already!
