### ISSUE TITLE
set up delivery of milestone2

### ISSUE THREAD

**Issue by dy-lin** [UBC-STAT/stat545.stat.ubc.ca#55]
This is the task listed on Asana-- I'm guessing this means...
- setting it up so that the second troubleshooting document shows up in their GitHub classroom project repositories
- updating the dashboard so that it is there

I don't see how to do the GitHub classroom in the instructor guide.
Does anyone know how to do this?

**Comment by vincenzocoia** [comment]
You got it!

> I don't see how to do the GitHub classroom in the instructor guide.
> Does anyone know how to do this?

Unfortunately not. I was hoping we would be able to make a pull request on everyone's repo, but I don't know how to do this. Maybe we can add a folder to the [template repository](https://github.com/stat545ubc-2020/template-collaborative-milestone1) and somehow initiate a PR through classroom.github.com? I guess the template repo wouldn't be appropriately named in that case...

Worst case scenario, we just put a link on the website.

**Comment by dy-lin** [comment]
I remember that Firas managed to add our pull requests to our repositories for STAT547, so I reached out to him about how he did this:

> Unfortunately I don’t have good news for you. They are still working on adding functionalities to GitHub Classroom to automate this. At the time when I needed it, there were two options:
> 
> 1) Ask students to add the template repo as an upstream master, and then pull changes. I thought this solution would not work for beginner git people.
> 
> 2) Clone all the repos to your computer and write a script to update the relevant text, add it to the repo, commit and push. Best to do this at a time when you know students aren’t working on this (tricky during COVID times)
> 
> I need up choosing a third option, which was that I just went into each repo online and manually updated the file and sent a PR. This worked for when there were <30 students (it took about 15 mins to do). Then I asked you to accept the PR.
> 
> There are some additional ideas here: https://education.github.community/t/updating-assignments-after-creation/23840 
> 
> Good luck!

Just reading through, option 2 looks like a nice option after the submission deadline for milestone1. I would consider pushing directly to the repository for most students, and then doing the pull request for those who have extensions? Thoughts?

**Comment by dy-lin** [comment]
**UPDATE**: I downloaded the new GitHub CLI interface, and wrote a script to create the pull requests: https://github.com/UBC-STAT/stat545.stat.ubc.ca/blob/master/instructor-guides/make-pull-request.sh

I've tested it a few times on the [template repo](https://github.com/stat545ubc-2020/template-collaborative-milestone1), seems to work fine. I'm not sure if the students get an alert about a pull request on their repos, so I'll create the requests tomorrow morning to avoid any confusion with milestone1.

**Comment by vincenzocoia** [comment]
Wow. Incredible!
