### ISSUE TITLE
Lecture 9A

### ISSUE THREAD

**Issue by vincenzocoia** [UBC-STAT/stat545.stat.ubc.ca#66]
@wvictor14 Let's use this Issue to discuss Thursday's lecture. Here's what I recommend you do:

1. Come up with two T/F quiz questions to ask as part of the think-pair-share activity.
    - Should ideally be points that are common misconceptions, or common errors. Could even allow for some wiggle room between true and false -- I like to think these promote thinking.
2. Come up with a lecture demonstration sheet, like the ones I've started making, that can be posted on the website.
    - Doesn't need to take up the whole lecture, get them to work on their worksheets if you finish before the end of class.

As for topics:

- Diana suggested a few worksheet points in the Week 5A guidance. 
- Many won't know about modelling, so best to make this more about the R objects than the models themselves. 
- I didn't teach them about lists yet, and would like to avoid that for now. No big deal if lists comes up, but it wouldn't be a good idea to spend much time on what a list is. This is coming in STAT 545B.

It would be nice if I could see a pull request of (1) and (2) above, but it's also no big deal if this doesn't happen.

Some admin stuff you'll need to do:

- [x] Don't forget to record the lecture -- I'll remind you.
- [x] Once the quiz is ready, you'll need to put this on Canvas. This can be prepared at anytime. This involves:
    - Making the assessment "available" starting 9:30am on Thursday.
    - Making the answers available starting 11:00am on Thursday.
    - Making the assessment due Friday at 11:00am.
    - Make a "participation" question with one answer, "click here for full marks". It should be worth 1 mark.
    - Make the two T/F questions. Make sure they are worth 0 marks. 
- [x] After lecture, post the updated demo on the main course dashboard, and the Week 5A guidance page.
- [ ] Post the lecture to canvas. [Instructions from the Instructors Guide](https://github.com/UBC-STAT/stat545.stat.ubc.ca/blob/master/instructor-guides/uploading_videos.md)

As always, feel free to ask me for help anytime!

**Comment by wvictor14** [comment]
Thanks for the directions @vincenzocoia ! 

I'm wondering for the demo if I can lean on the previous year's [exercise worksheet](https://github.com/UBC-STAT/stat-545-guidebook/blob/master/tutorials/cm014-exercise.Rmd)?

And I'll put this demo in a PR.

**Comment by vincenzocoia** [comment]
Yep, the demo is good to reuse.

**Comment by vincenzocoia** [comment]
I added the quiz to canvas -- I figured it's easier if I do that, because I'm already in the swing of things :)

**Comment by vincenzocoia** [comment]
Both quizzes have been prepared on Zoom, too -- you'll only need to select the quiz during lecture, and it'll appear!

**Comment by vincenzocoia** [comment]
Also, maybe I'll record the session, and will post the video to canvas -- as before, I'm already in the swing of things, and I can probably do it in half as much time as someone else at this point.

**Comment by wvictor14** [comment]
> Both quizzes have been prepared on Zoom, too -- you'll only need to select the quiz during lecture, and it'll appear!

Thank you!

**Comment by wvictor14** [comment]
Trying to add the screencast to the correct playlist. I don't see an option to add it though... This is what it looks like on my screen:

![image](https://user-images.githubusercontent.com/22013187/95505218-db8fa000-0962-11eb-91fe-c916fb8abfb8.png)

**Comment by vincenzocoia** [comment]
Was the video uploaded via `My Media`? I can't seem to find it -- but then again, maybe canvas still needs to process the video (canvas takes a while to do this).

I see something different on Media Gallery, though -- you have a half-filled-in circle with a check-mark in the upper-right corner, whereas I have another logo with three horizontal  bars.

If the video is uploaded, I can move it to the correct playlist.

**Comment by wvictor14** [comment]
I did upload it yesterday. It shows up in "media gallery" 
![image](https://user-images.githubusercontent.com/22013187/95627500-2c6dca00-0a31-11eb-8a07-ccf641a380eb.png)

**Comment by vincenzocoia** [comment]
So weird, I don't see it... Maybe I should wait until Tuesday?

**Comment by wvictor14** [comment]
Here I've uploaded the video to google drive: https://drive.google.com/file/d/18zFvFTvDlCFwIdbKPsbDQdwBqUU64VMG/view?usp=sharing

**Comment by vincenzocoia** [comment]
Thank you!!
